config/routes.rb
Rails.application.routes.draw do
  resources :news
  resources :categories
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/news.rb
class News < ApplicationRecord
  belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:title)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @navtab_content1 = News.where(category: 1)
  end
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]

  # GET /news
  # GET /news.json
  def index
    @news = News.all
  end

  # GET /news/1
  # GET /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = News.new
  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    @news = News.new(news_params)

    respond_to do |format|
      if @news.save
        format.html { redirect_to @news, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news.update(news_params)
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to news_index_url, notice: 'News was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:title, :link, :publish_date, :is_online, :category_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :category_title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.title %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @category.title %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/home/index.html.erb
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag "img01.jpg", alt:"01" , width:"100%"  %>
    </div>
    <div class="carousel-item">
      <%= image_tag "img02.jpg", alt:"01" , width:"100%"  %>
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
</br>
<div>
  <span class=" h4 pl-2 title">最新消息</span>
</div>
</br>
<div class="cantainer">
  <div class="row">
    <div class="col-9" style="border:1px #ccc solid;">
      <table>
        <tr>
          <td>資訊</td>
        </tr>
        <tr>
          <td> <a href="#" class="title-1">國立臺北商業大學建校一百周年特刊</a> </td>
        </tr>
        <tr >
          <td><a href="#" class="title-1">《活動新訊》百周年校慶電影節</a> </td>
        </tr>
        <tr>
          <td><a href="#" class="title-1">「活動新訊」-百周年校慶公益點燈 </a> </td>
        </tr>

      </table>
    </div>
    <div class="col-3" style="border:1px #ccc solid;">
      <table>
        <tr>
          <td>日期</td>
        </tr>
        <tr>
          <td><a href="#" class="title-1">2017-12-8</a></td>
        </tr>
        <tr>
          <td><a href="#" class="title-1">2017-12-5</a></td>
        </tr>
        <tr>
          <td><a href="#" class="title-1">2017-12-1</a></td>
        </tr>
      </table>
    </div>
  </div>
</div>
</br>
<div>
  <span class=" h4 pl-2 title">活動花絮</span>
</div>
</br>
<div class="card" style="width: 18rem;">
  <%= image_tag "d01.jpg", alt:"01" , width:"100%"  %>
  <div class="card-body">
    <p class="card-text"> 【公告】大學校長暨北商榮譽講座高峰論壇</p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MySchool</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/footer" %>
    </div>
  </body>
</html>

app/views/news/_form.html.erb
<%= form_with(model: news, local: true) do |form| %>
  <% if news.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(news.errors.count, "error") %> prohibited this news from being saved:</h2>

      <ul>
      <% news.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :news_title %>
  </div>

  <div class="field">
    <%= form.label :link %>
    <%= form.text_field :link, id: :news_link %>
  </div>

  <div class="field">
    <%= form.label :publish_date %>
    <%= form.date_select :publish_date, id: :news_publish_date %>
  </div>

  <div class="field">
    <%= form.label :is_online %>
    <%= form.check_box :is_online, id: :news_is_online %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.text_field :category_id, id: :news_category_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/news/edit.html.erb
<h1>Editing News</h1>

<%= render 'form', news: @news %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

app/views/news/index.html.erb
<p id="notice"><%= notice %></p>

<h1>News</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Link</th>
      <th>Publish date</th>
      <th>Is online</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @news.each do |news| %>
      <tr>
        <td><%= news.title %></td>
        <td><%= news.link %></td>
        <td><%= news.publish_date %></td>
        <td><%= news.is_online %></td>
        <td><%= news.category %></td>
        <td><%= link_to 'Show', news %></td>
        <td><%= link_to 'Edit', edit_news_path(news) %></td>
        <td><%= link_to 'Destroy', news, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New News', new_news_path %>

app/views/news/new.html.erb
<h1>New News</h1>

<%= render 'form', news: @news %>

<%= link_to 'Back', news_index_path %>

app/views/news/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @news.title %>
</p>

<p>
  <strong>Link:</strong>
  <%= @news.link %>
</p>

<p>
  <strong>Publish date:</strong>
  <%= @news.publish_date %>
</p>

<p>
  <strong>Is online:</strong>
  <%= @news.is_online %>
</p>

<p>
  <strong>Category:</strong>
  <%= @news.category %>
</p>

<%= link_to 'Edit', edit_news_path(@news) %> |
<%= link_to 'Back', news_index_path %>

app/views/shared/_navbar.html.erb
<!--圖片-->
<div class="logo">
  <%= image_tag "logo.png", alt:"國立臺北商業大學" , width:"60%"  %>
</div>

<nav aria-label="breadcrumb" class="mt-2 mb-3 "  >
  <div class="bread">
    <ol class="breadcrumb p-0 mb-0">
      <li class="breadcrumb bread-des mb-0 pr-0 pl-1"><img src="http://100th.ntub.edu.tw/style/25/images/hd_nav_li.gif" class="mr-1 p-1"><a href="#" style="color:rgb(255, 255, 255)" class="mr-0 pr-0" style="text-decoration:none">百年校史</a></li>
      <li class="breadcrumb bread-des mb-0 pr-0 pl-1"><img src="http://100th.ntub.edu.tw/style/25/images/hd_nav_li.gif" class="mr-1 p-1"><a href="#" style="color:rgb(255, 255, 255)" class="mr-0 pr-0" style="text-decoration:none">百年盛典</a></li>
      <li class="breadcrumb bread-des mb-0 pr-0 pl-1"><img src="http://100th.ntub.edu.tw/style/25/images/hd_nav_li.gif" class="mr-1 p-1"><a href="#" style="color:rgb(255, 255, 255)" class="mr-0 pr-0" style="text-decoration:none">校友歡聚</a></li>
      <li class="breadcrumb bread-des mb-0 pr-0 pl-1"><img src="http://100th.ntub.edu.tw/style/25/images/hd_nav_li.gif" class="mr-1 p-1"><a href="#" style="color:rgb(255, 255, 255)" class="mr-0 pr-0" style="text-decoration:none">慶祝活動</a></li>
      <li class="breadcrumb bread-des mb-0 pr-4 pl-1"><img src="http://100th.ntub.edu.tw/style/25/images/hd_nav_li.gif" class="mr-1 p-1"><a href="#" style="color:rgb(255, 255, 255)" class="mr-0 pr-0" style="text-decoration:none">建設北商</a></li>
    </ol>
  </div>
</nav>